GET http://localhost:3000

### Register

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "nguyentam2@gmail.com",
    "password": "123456789"
}

### Login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "nguyentam2@gmail.com",
    "password": "123456789"
}


### Share movie

POST http://localhost:3000/movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ndXllbnRhbTJAZ21haWwuY29tIiwiaWF0IjoxNjgwNzYyNzA4LCJleHAiOjE2ODA4NDkxMDh9.6l2njt3ZC-el0XayCPqYupO1yZyV4YW5nW_w4V9BevY

{
    "url": "https://www.youtube.com/watch?v=wRIll-G0SQE"
}

### get all movice

GET http://localhost:3000/movie
Content-Type: application/json